version: "3.8"

services:
  live:
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
    - 4000:4000
    command: bazel run //site:live
    volumes:
    - .:/src/workspace/envoy-website
    - ~/.cache/bazel:/$HOME/.cache/bazel
    - ~/.cache/bazelisk:/$HOME/.cache/bazelisk
    working_dir: /src/workspace/envoy-website
    environment:
      LOCAL_UID: ${UID:?"`UID` must be set, try `export UID`"}
      LOCAL_USER_NAME: $USERNAME
      LOCAL_USER_HOME: $HOME

  live_docs:
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
    - 4000:4000
    command: |
      bash -c '\
          bazel run --action_env=ENVOY_COMMIT="$$(bazel run //docs:latest_version)" \
              //site:live_docs'
    volumes:
    - .:/src/workspace/envoy-website
    - ~/.cache/bazel:/$HOME/.cache/bazel
    - ~/.cache/bazelisk:/$HOME/.cache/bazelisk
    working_dir: /src/workspace/envoy-website
    environment:
      LOCAL_UID: ${UID:?"`UID` must be set, try `export UID`"}
      LOCAL_USER_NAME: $USERNAME
      LOCAL_USER_HOME: $HOME

  build:
    build:
      context: docker
      dockerfile: Dockerfile
    command: ./build-website.sh
    volumes:
    - .:/src/workspace/envoy-website
    - ~/.cache/bazel:/$HOME/.cache/bazel
    - ~/.cache/bazelisk:/$HOME/.cache/bazelisk
    working_dir: /src/workspace/envoy-website
    environment:
      LOCAL_UID: ${UID:?"`UID` must be set, try `export UID`"}
      LOCAL_USER_NAME: $USERNAME
      LOCAL_USER_HOME: $HOME

  update:
    build:
      context: docker
      dockerfile: Dockerfile
    command: ./sync_envoy.sh
    volumes:
    - .:/src/workspace/envoy-website
    - ${ENVOY_SRC_DIR:-../envoy}:/src/workspace/envoy
    - ~/.cache/bazel:/$HOME/.cache/bazel
    - ~/.cache/bazelisk:/$HOME/.cache/bazelisk
    working_dir: /src/workspace/envoy-website
    environment:
      LOCAL_UID: ${UID:?"`UID` must be set, try `export UID`"}
      LOCAL_USER_NAME: $USERNAME
      LOCAL_USER_HOME: $HOME
      ENVOY_SRC_DIR: ../envoy
      COMMITTER_NAME: ${COMMITTER_NAME}
      COMMITTER_EMAIL: ${COMMITTER_EMAIL}

  static:
    image: nginx
    volumes:
    - ./_site:/usr/share/nginx/html:z
    ports:
    - 7000:80
